# syntax=docker/dockerfile:1.2

# STAGE 1: build the executable
FROM  localhost/afb-iso15118_almalinux AS builder

RUN <<EOF
microdnf  --nodocs -y install git findutils which
microdnf  --nodocs -y install crypto-policies
EOF

RUN <<EOF
# prepare tiny-root-fs with afb and minimal dependencies
git clone https://github.com/fulup-bzh/mkTinyRootFs &&
(cd mkTinyRootFs &&
# wget https://github.com/fulup-bzh/mkTinyRootFs/raw/master/Samples/oci-sample.conf &&
cat >> minimal-iso15118.conf <<!!conf
# executable searched from path
BINLIST="
    /lib64/ld-linux-x86-64.so.2
    /usr/bin/bash
    /usr/bin/grep
    /usr/sbin/ip
    /usr/bin/pkill
    /usr/bin/clear
    /usr/bin/afb-binder
    /usr/redpesk/iso15118-simulator-rs/lib/libafb_sim15118_evcc.so
    /usr/redpesk/iso15118-simulator-rs/lib/libafb_sim15118_evse.so
    /usr/redpesk/injector-binding-rs/lib/libafb_injector.so
    /usr/lib/libiso15118.so.1.0
    /usr/bin/pcap-iso15118
    /usr/bin/binding-start-evcc
    /usr/bin/binding-start-evse
    /usr/bin/ls
    /usr/bin/coreutils
    /usr/bin/ldd
"

SHARELIST="
    /usr/share/iso15118-simulator-rs/*
    /usr/share/afb-ui-devtools/binder/*
    /etc/crypto-policies/back-ends/*
    /etc/crypto-policies/*
    /usr/share/crypto-policies/DEFAULT/*
    /usr/share/crypto-policies/*
"
!!conf
./mkTinyRootFs.bash config=minimal-iso15118.conf target=/tmp/stage2-rootfs

cd /tmp/stage2-rootfs/

#mv /tmp/stage2-rootfs/lib64 /tmp/stage2-rootfs/usr/
#mv /tmp/stage2-rootfs/lib /tmp/stage2-rootfs/usr/
#ln -s /usr/lib64 /tmp/stage2-rootfs/lib64
#ln -s /usr/lib /tmp/stage2-rootfs/lib

echo "_________________"
du -h --max-depth=1 .
echo "_________________"
du -h --max-depth=1 ./etc
echo "_________________"
du -h --max-depth=1 ./usr
echo "_________________"
du -h --max-depth=1 ./usr/bin
echo "_________________"
du -h --max-depth=1 ./lib64
echo "_________________"
ls -l -h ./lib64 | sort -h
echo "_________________"
du -h --max-depth=1 ./usr/sbin
echo "_________________"
du -h --max-depth=1 ./usr/lib
echo "_________________"
ls -l -h ./usr/lib | sort -h
echo "_________________"
du -h --max-depth=1 ./usr/redpesk
echo "_________________"
du -h --max-depth=1 ./usr/share
echo "_________________"
find . | sort
echo "_________________"
)

EOF

# # # STAGE 2: build the container
FROM scratch As final

COPY --from=builder /tmp/stage2-rootfs/ /

ENV LD_LIBRARY_PATH="/usr/lib"
